import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import NavigationBar from "@/components/navigation";
import MainSection from "@/markup/main_section";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>E Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar/>
      <MainSection/>

    </>
  );
}
